'use client'
import { AuthProvider } from '@/Contexts/useAuth';
import { LocationProvider } from '@/Contexts/location';
import './globals.css'
import { usePathname } from 'next/navigation';
export const metadata = {
  title: 'Zipper',
  description: 'Generated by create next app',
}
import Sidebar from '@/Components/Sidebar';

export default function RootLayout({ children }) {


  const pathname = usePathname();
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet"
      href="https://unpkg.com/boxicons@latest/css/boxicons.min.css"/>
        <link rel="icon" href="./lol.jpg" sizes="any" />
      </head>
      <AuthProvider>
      <LocationProvider>
        <body>
          <script src="https://accounts.google.com/gsi/client" async></script>
            {pathname !== "/login" && pathname !== "/"? <div className='flex'>  
            <Sidebar />
              {children}
              </div> : [children]
            }
          </body>
          </LocationProvider>
          </AuthProvider>
    </html>
  )
}
